# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# SWAGGER (SPRINGDOC)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# GOOGLE OAUTH2 (ĐÃ CẬP NHẬT MỚI)
# ===============================
spring.security.oauth2.client.registration.google.client-id=587116731741-kjvuh433rc3841mp34pjg1e2sbslnusn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# MAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buinguyenhuy767@gmail.com
spring.mail.password=pblhcxdebcojxudp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Ép hiện chi tiết các bước bảo mật ra Terminal
logging.level.org.springframework.security=DEBUG

#Supabase
supabase.url=${SUPABASE_URL:dummy}
supabase.key=${SUPABASE_KEY:dummy}
supabase.bucket=${SUPABASE_BUCKET:post-images}

#SMS
vonage.api.key=554161c3
vonage.api.secret=OTNebOvU8iaPvPmi
vonage.sms.from=VuaTroApp